Repository specklesystems/speckle-sharp, pull requests merged in 2022-08, with the labels that each got.

#1462 fix(ci): Removes -mac suffix from slug as OS is now it's own parameter
  .circleci/scripts/config-generator.py
Labels: bug

#1479 Archicad/dotnet5
  .circleci/scripts/config-template.yml
Labels: hotfix-2.7

#1529 CORE: Adds extension method to extract all messages from an Exception
  ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
  Core/Core/Models/Extensions.cs
  Core/Core/Models/Extras.cs
  Core/Tests/ExceptionTests.cs
Labels: enhancement

#1523 Added static accessor to `DynamicBase.GetInstanceMembers`
  Core/Core/Models/DynamicBase.cs
  Core/Tests/BaseTests.cs
Labels: core
